name: Build with poetry
inputs:
  python-version:
    required: false
    default: 3.9

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{inputs.python-version}}
    - name: Install depedencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install poetry  
    - name: Build with poetry
      shell: bash
      run: |
        poetry version $(git tag --points-at HEAD)
        poetry install