# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Package

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/poetry-setup
      - name: Run linters
        run: poetry run flake8
    continue-on-error: true

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/poetry-setup
        with:
          python-version: ${{matrix.python-version}}
      - name: Pytest
        run: |
          poetry run pytest tests -s
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/poetry-setup
      - name: Build with poetry
        run: poetry build
      - name: Capture artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Python Package
          path: dist/*.whl
      - name: Install wheel
        run: pip install dist/*.whl
